/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.Archivo;
import Clase.Libro;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Listar extends javax.swing.JDialog {
    private Archivo archivo;
    
    /**
     * Creates new form Listar
     */
    public Listar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Listar Libros");
        this.getContentPane().setBackground(color(165, 42, 42));
        tblRegistro.setBackground(color(249, 239, 195));
    }
    
    Color color(int r, int g, int b){
        return new Color(r, g, b);
    }
    
    public void asignarArchivo(Archivo a) {
        archivo = a;
    }
    
    void listar() {
        ArrayList<Libro> libros = archivo.leerArchivo();
        String columna[] = {"Código", "Título", "Autor", "País", "Año"};
        int[] ancho = {80, 385, 175, 90, 50};
        
        DefaultTableModel mt = new DefaultTableModel(null, columna){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }        
        };
        
        tblRegistro.setModel(mt);
        
        for(int i = 0; i < tblRegistro.getColumnCount(); i++){
            tblRegistro.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
        }
        
        for(Libro x: libros){
            String cod = String.format("%010d", x.getCodigo());
            mt.addRow(new Object[]{cod, x.getTitulo(), x.getAutor(), x.getPais(), x.getAño()});
        }
    }
    
    void seleccionar(int fila, MouseEvent evt) {
        int cod = Integer.parseInt(tblRegistro.getValueAt(fila, 0).toString());

        if(evt.getButton() == MouseEvent.BUTTON1){
            VerLibro ver = new VerLibro(new javax.swing.JFrame(), true);
            ver.asignarArchivo(archivo);
            ver.recibirDatos(cod);
            ver.setVisible(true);
        } else if(evt.getButton() == MouseEvent.BUTTON3){
            int y = evt.getY();
            
            if((y >= fila * 16) && (y <= (fila * 16) + 16)){
                pMnModificarEliminar.show(this, 150, (fila * 16) + 19);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMnModificarEliminar = new javax.swing.JPopupMenu();
        mnItModificar = new javax.swing.JMenuItem();
        mnItEliminar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistro = new javax.swing.JTable();

        mnItModificar.setText("Modificar");
        mnItModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItModificarActionPerformed(evt);
            }
        });
        pMnModificarEliminar.add(mnItModificar);

        mnItEliminar.setText("Eliminar");
        mnItEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItEliminarActionPerformed(evt);
            }
        });
        pMnModificarEliminar.add(mnItEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistroMouseClicked
        int fila = tblRegistro.getSelectedRow();
        if(fila != -1) seleccionar(fila, evt);
    }//GEN-LAST:event_tblRegistroMouseClicked

    private void mnItModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItModificarActionPerformed
        ArrayList<Libro> libros = archivo.leerArchivo();
        int fila = tblRegistro.getSelectedRow();
        int cod = Integer.parseInt(tblRegistro.getValueAt(fila, 0).toString());
        
        Modificar modificar = new Modificar(new javax.swing.JFrame(), true);
        modificar.asignarArchivo(archivo);
        modificar.codigo(cod);
        modificar.recibirDatos();
        modificar.setVisible(true);
        listar();
    }//GEN-LAST:event_mnItModificarActionPerformed

    private void mnItEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItEliminarActionPerformed
        ArrayList<Libro> libros = archivo.leerArchivo();
        int fila = tblRegistro.getSelectedRow();
        int cod = Integer.parseInt(tblRegistro.getValueAt(fila, 0).toString());
        
        for(Libro x: libros){
            if(cod == x.getCodigo()) archivo.eliminarArchivo(cod, x.getTitulo());
        }
        
        listar();
    }//GEN-LAST:event_mnItEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Listar dialog = new Listar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnItEliminar;
    private javax.swing.JMenuItem mnItModificar;
    private javax.swing.JPopupMenu pMnModificarEliminar;
    private javax.swing.JTable tblRegistro;
    // End of variables declaration//GEN-END:variables
}
