/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.Archivo;
import Clase.Libro;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Modificar extends javax.swing.JDialog {
    private Archivo archivo;
    private int codigo;
    
    /**
     * Creates new form Modificar
     */
    public Modificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Modificar Libro");
        setIconImage(new ImageIcon(getClass().getResource("/Icono/Icono.png")).getImage());
        this.getContentPane().setBackground(color(165, 42, 42));
        dskModificar.setBackground(color(249, 239, 195));
    }
    
    Color color(int r, int g, int b){
        return new Color(r, g, b);
    }
    
    public void asignarArchivo(Archivo a) {
        archivo = a;
    }
    
    public void codigo(int cod) {
        codigo = cod;
    }
    
    public void recibirDatos() {
        ArrayList<Libro> libros = archivo.leerArchivo();
        
        for(Libro x: libros){
            if(codigo == x.getCodigo()){
                txtTitulo.setText(x.getTitulo());
                txtAutor.setText(x.getAutor());
                txtPais.setText(x.getPais());
                txtAño.setText(String.valueOf(x.getAño()));
            }
        }
    }
    
    void modificar() {
        if((nulo() == false) && (entero(txtAño.getText()) == true)){
            String tit = txtTitulo.getText();
            String aut = txtAutor.getText();
            String p = txtPais.getText();
            int a = Integer.parseInt(txtAño.getText());
            
            if(libroIgual(tit) == false){
                Libro L = new Libro(codigo, tit, aut, p, a);
                archivo.modificarArchivo(L);
                limpiar();
                this.dispose();
            } else{
                txtTitulo.setText("");
                JOptionPane.showMessageDialog(null, "El libro ya está registrado");
            }
        } else if(nulo() == true){
            JOptionPane.showMessageDialog(null, "Llene todos los datos");
        } else if(entero(txtAño.getText()) == false){
            txtAño.setText("");
            JOptionPane.showMessageDialog(null, "El año debe de ser entero");
        }
    }
    
    boolean nulo() {
        if("".equals(txtTitulo.getText())) return true;
        if("".equals(txtAutor.getText())) return true;
        if("".equals(txtPais.getText())) return true;
        if("".equals(txtAño.getText())) return true;
        
        return false;
    }
    
    boolean entero(String cadEntero) {
        for(int i = 0; i < cadEntero.length(); i++){
            switch(cadEntero.charAt(i)){
                case '0': case '1': case '2': case '3': case '4': case '5': 
                case '6': case '7': case '8': case '9': break;
                default: return false;
            }
        }
        
        return true;
    }
    
    boolean libroIgual(String lib) {
        ArrayList<Libro> libros = archivo.leerArchivo();
        
        for(Libro x: libros){
            if(lib == x.getTitulo()){
                if(codigo != x.getCodigo()) return true;
            }
        }
        
        return false;
    }
    
    void limpiar() {
        txtTitulo.setText("");
        txtAutor.setText("");
        txtPais.setText("");
        txtAño.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskModificar = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbPais = new javax.swing.JLabel();
        lbAño = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dskModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificar Libro"));

        lbTitulo.setText("Título");

        lbPais.setText("País");

        lbAño.setText("Año");

        lbAutor.setText("Autor");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dskModificarLayout = new javax.swing.GroupLayout(dskModificar);
        dskModificar.setLayout(dskModificarLayout);
        dskModificarLayout.setHorizontalGroup(
            dskModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(110, 110, 110))
            .addGroup(dskModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dskModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dskModificarLayout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitulo))
                    .addGroup(dskModificarLayout.createSequentialGroup()
                        .addComponent(lbAutor)
                        .addGap(18, 18, 18)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dskModificarLayout.createSequentialGroup()
                        .addComponent(lbPais)
                        .addGap(18, 18, 18)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lbAño)
                        .addGap(18, 18, 18)
                        .addComponent(txtAño, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dskModificarLayout.setVerticalGroup(
            dskModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dskModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dskModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dskModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPais)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar dialog = new Modificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel dskModificar;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbAño;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
