/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.Archivo;
import Clase.Libro;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Registrar extends javax.swing.JDialog {
    private Archivo archivo;
    
    /**
     * Creates new form Registrar
     */
    public Registrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Registrar Libro");
        this.getContentPane().setBackground(color(165, 42, 42));
        dskRegistrar.setBackground(color(249, 239, 195));
    }
    
    Color color(int r, int g, int b){
        return new Color(r, g, b);
    }
    
    public void asignarArchivo(Archivo a) {
        archivo = a;
    }
    
    void registrar() {
        if((nulo() == false) && (entero(txtAño.getText()) == true)){
            String tit = txtTitulo.getText();
            String aut = txtAutor.getText();
            String p = txtPais.getText();
            int a = Integer.parseInt(txtAño.getText());
            int cod = 0;
            
            cod = hash(cod, aut, 1000000, 10000);
            cod = hash(cod, p, 1000, 1000);
            cod = hash(cod, tit, 1, 1000);
            
            if(cod < 0) cod *= -1;
            while(codigoIgual(cod) == true) cod++;
            
            if(libroIgual(tit) == false){
                Libro L = new Libro(cod, tit, aut, p, a);
                archivo.escribirArchivo(L);
                limpiar();
                this.dispose();
            } else{
                txtTitulo.setText("");
                JOptionPane.showMessageDialog(null, "El libro ya está registrado");
            }
        } else if(nulo() == true){
            JOptionPane.showMessageDialog(null, "Llene todos los datos");
        } else if(entero(txtAño.getText()) == false){
            txtAño.setText("");
            JOptionPane.showMessageDialog(null, "El año debe de ser entero");
        }
    }
    
    int hash(int cod, String cad, int num, int max) {
        int suma = 0;
        
        for(int i = 0; i < cad.length(); i++){
            suma += cad.charAt(i);
        }
        
        if(suma < max){
            cod += suma * num;
        } else cod += (suma % max) * num;
        
        return cod;
    }
    
    boolean nulo() {
        if("".equals(txtTitulo.getText())) return true;
        if("".equals(txtAutor.getText())) return true;
        if("".equals(txtPais.getText())) return true;
        if("".equals(txtAño.getText())) return true;
        
        return false;
    }
    
    boolean entero(String cadEntero) {
        for(int i = 0; i < cadEntero.length(); i++){
            switch(cadEntero.charAt(i)){
                case '0': case '1': case '2': case '3': case '4': case '5': 
                case '6': case '7': case '8': case '9': break;
                default: return false;
            }
        }
        
        return true;
    }
    
    boolean codigoIgual(int cod) {
        ArrayList<Libro> libros = archivo.leerArchivo();
        
        for(Libro x: libros){
            if(cod == x.getCodigo()) return true;
        }
        
        return false;
    }
    
    boolean libroIgual(String lib) {
        ArrayList<Libro> libros = archivo.leerArchivo();
        
        for(Libro x: libros){
            if(lib == x.getTitulo()) return true;
        }
        
        return false;
    }
    
    void limpiar() {
        txtTitulo.setText("");
        txtAutor.setText("");
        txtPais.setText("");
        txtAño.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskRegistrar = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbPais = new javax.swing.JLabel();
        lbAño = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dskRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Libro"));

        lbTitulo.setText("Título");

        lbPais.setText("País");

        lbAño.setText("Año");

        lbAutor.setText("Autor");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dskRegistrarLayout = new javax.swing.GroupLayout(dskRegistrar);
        dskRegistrar.setLayout(dskRegistrarLayout);
        dskRegistrarLayout.setHorizontalGroup(
            dskRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskRegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(109, 109, 109))
            .addGroup(dskRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dskRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dskRegistrarLayout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitulo))
                    .addGroup(dskRegistrarLayout.createSequentialGroup()
                        .addComponent(lbAutor)
                        .addGap(18, 18, 18)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dskRegistrarLayout.createSequentialGroup()
                        .addComponent(lbPais)
                        .addGap(18, 18, 18)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lbAño)
                        .addGap(18, 18, 18)
                        .addComponent(txtAño, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dskRegistrarLayout.setVerticalGroup(
            dskRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dskRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dskRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dskRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPais)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registrar dialog = new Registrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel dskRegistrar;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbAño;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
